"""publishing media: audio, video, thumbnail and concat, one test group per capability, plus the limits,
the refusals and determinism. They need ffmpeg and ffprobe and skip without them; the Dockerfile.media
test stage and CI run them in the image, with no network. Fixtures are generated by ffmpeg itself
(lavfi sources), so no binary file is committed.
"""
import shutil
import subprocess
import sys

import pytest

from publishing import media

needs_ffmpeg = pytest.mark.skipif(not (shutil.which("ffmpeg") and shutil.which("ffprobe")),
                                  reason="ffmpeg is not installed")
pytestmark = needs_ffmpeg


def ff(*args):
    subprocess.run(["ffmpeg", "-v", "error", "-y", *args], check=True, stdin=subprocess.DEVNULL)


def probe(path, entries, stream=None):
    cmd = ["ffprobe", "-v", "error", "-of", "csv=p=0", "-show_entries", entries]
    if stream:
        cmd += ["-select_streams", stream]
    return subprocess.run([*cmd, str(path)], capture_output=True, text=True, check=True).stdout.strip()


def cli(*args, cwd=None):
    return subprocess.run([sys.executable, "-m", "publishing.cli", "media", *args], capture_output=True,
                          text=True, cwd=cwd)


@pytest.fixture(scope="module")
def clip(tmp_path_factory):
    """A 2 s 160x120 10 fps MP4 with a 440 Hz tone."""
    d = tmp_path_factory.mktemp("clip")
    out = d / "clip.mp4"
    ff("-f", "lavfi", "-i", "testsrc=size=160x120:rate=10:duration=2", "-f", "lavfi",
       "-i", "sine=frequency=440:duration=2", "-c:v", "libx264", "-pix_fmt", "yuv420p", "-c:a", "aac",
       "-shortest", str(out))
    return out


@pytest.fixture(scope="module")
def tone(tmp_path_factory):
    out = tmp_path_factory.mktemp("tone") / "tone.wav"
    ff("-f", "lavfi", "-i", "sine=frequency=330:duration=1", str(out))
    return out


# --- audio ------------------------------------------------------------------------------------

@pytest.mark.parametrize("suffix,codec", [(".mp3", "mp3"), (".m4a", "aac"), (".opus", "opus"),
                                          (".flac", "flac"), (".wav", "pcm_s16le"), (".ogg", "vorbis")])
def test_audio_formats(clip, tmp_path, suffix, codec):
    out = media.audio(clip, tmp_path / f"a{suffix}")
    assert probe(out, "stream=codec_name", "a:0") == codec
    assert probe(out, "stream=codec_type") == "audio"  # no video stream came along


def test_audio_bitrate(clip, tmp_path):
    out = media.audio(clip, tmp_path / "a.mp3", bitrate="64k")
    assert 40_000 < int(probe(out, "format=bit_rate")) < 90_000


def test_audio_from_audio(tone, tmp_path):
    out = media.audio(tone, tmp_path / "t.flac")
    assert abs(float(probe(out, "format=duration")) - 1.0) < 0.1


# --- video ------------------------------------------------------------------------------------

def test_video_mp4(clip, tmp_path):
    out = media.video(clip, tmp_path / "v.mp4")
    assert probe(out, "stream=codec_name", "v:0") == "h264"
    assert probe(out, "stream=codec_name", "a:0") == "aac"
    assert probe(out, "stream=width,height", "v:0") == "160,120"


def test_video_webm_scaled(clip, tmp_path):
    out = media.video(clip, tmp_path / "v.webm", height=60)
    assert probe(out, "stream=codec_name", "v:0") == "vp9"
    assert probe(out, "stream=codec_name", "a:0") == "opus"
    assert probe(out, "stream=width,height", "v:0") == "80,60"


def test_video_without_audio(tmp_path):
    silent = tmp_path / "s.mp4"
    ff("-f", "lavfi", "-i", "testsrc=size=64x64:rate=5:duration=1", "-pix_fmt", "yuv420p", str(silent))
    out = media.video(silent, tmp_path / "o.mp4")
    assert probe(out, "stream=codec_type") == "video"


def test_video_strips_source_metadata(tmp_path):
    src = tmp_path / "m.mp4"
    ff("-f", "lavfi", "-i", "testsrc=size=64x64:rate=5:duration=1", "-pix_fmt", "yuv420p",
       "-metadata", "title=SecretTitle", str(src))
    out = media.video(src, tmp_path / "o.mp4")
    assert b"SecretTitle" not in out.read_bytes()


# --- thumbnails -------------------------------------------------------------------------------

def test_thumbnail_png(clip, tmp_path):
    out = media.thumbnail(clip, tmp_path / "t.png", at=1.0)
    assert out.read_bytes()[:8] == b"\x89PNG\r\n\x1a\n"
    assert probe(out, "stream=width,height") == "160,120"


def test_thumbnail_jpg_width(clip, tmp_path):
    out = media.thumbnail(clip, tmp_path / "t.jpg", width=80)
    assert out.read_bytes()[:3] == b"\xff\xd8\xff"
    assert probe(out, "stream=width,height") == "80,60"


def test_thumbnail_times_differ(clip, tmp_path):
    a = media.thumbnail(clip, tmp_path / "a.png", at=0)
    b = media.thumbnail(clip, tmp_path / "b.png", at=1.5)
    assert a.read_bytes() != b.read_bytes()


def test_thumbnail_past_end(clip, tmp_path):
    with pytest.raises(media.UsageError):
        media.thumbnail(clip, tmp_path / "t.png", at=60)
    assert not (tmp_path / "t.png").exists()


# --- concat -----------------------------------------------------------------------------------

def test_concat_joins_in_order(clip, tmp_path):
    out = media.concat([clip, clip, clip], tmp_path / "all.mp4")
    assert abs(float(probe(out, "format=duration")) - 6.0) < 0.3
    assert probe(out, "stream=codec_name", "v:0") == "h264"


def test_concat_audio(tone, tmp_path):
    out = media.concat([tone, tone], tmp_path / "two.wav")
    assert abs(float(probe(out, "format=duration")) - 2.0) < 0.1


def test_concat_path_with_quote(tone, tmp_path):
    odd = tmp_path / "it's.wav"
    shutil.copy(tone, odd)
    out = media.concat([odd, tone], tmp_path / "two.wav")
    assert abs(float(probe(out, "format=duration")) - 2.0) < 0.1


def test_concat_needs_two_and_one_type(clip, tone, tmp_path):
    with pytest.raises(media.UsageError):
        media.concat([clip], tmp_path / "x.mp4")
    with pytest.raises(media.UsageError):
        media.concat([clip, tone], tmp_path / "x.mp4")


def test_concat_mismatch_is_an_error(tone, tmp_path):
    other = tmp_path / "o.wav"
    ff("-f", "lavfi", "-i", "sine=frequency=330:duration=1", "-ar", "8000", str(other))
    out = tmp_path / "x.wav"
    try:
        media.concat([tone, other], out)
    except media.MediaError:
        assert not out.exists()


# --- determinism ------------------------------------------------------------------------------

@pytest.mark.parametrize("name", ["a.mp3", "a.m4a", "a.opus", "v.mp4", "v.webm", "t.png"])
def test_same_input_same_bytes(clip, tmp_path, name):
    fn = {"a": media.audio, "v": media.video, "t": media.thumbnail}[name[0]]
    one = fn(clip, tmp_path / "1" / name)
    two = fn(clip, tmp_path / "2" / name)
    assert one.read_bytes() == two.read_bytes()


# --- limits and refusals ----------------------------------------------------------------------

def test_never_overwrites(clip, tmp_path):
    out = tmp_path / "a.mp3"
    out.write_bytes(b"mine")
    with pytest.raises(media.UsageError):
        media.audio(clip, out)
    assert out.read_bytes() == b"mine"


def test_no_leftovers_after_success(clip, tmp_path):
    media.audio(clip, tmp_path / "a.mp3")
    assert [p.name for p in tmp_path.iterdir()] == ["a.mp3"]


def test_size_cap(clip, tmp_path):
    with pytest.raises(media.MediaError, match="cap"):
        media.audio(clip, tmp_path / "a.wav", max_bytes=2000)
    assert list(tmp_path.iterdir()) == []


def test_duration_cap(clip, tmp_path):
    with pytest.raises(media.MediaError, match="cap"):
        media.audio(clip, tmp_path / "a.mp3", max_seconds=1)
    assert list(tmp_path.iterdir()) == []


def test_time_cap_kills_ffmpeg(tmp_path):
    big = tmp_path / "big.mp4"
    ff("-f", "lavfi", "-i", "testsrc2=size=1280x720:rate=30:duration=20", "-c:v", "libx264", "-preset",
       "ultrafast", "-pix_fmt", "yuv420p", str(big))
    with pytest.raises(media.MediaError, match="timed out"):
        media.video(big, tmp_path / "o" / "slow.webm", timeout=0.3)
    assert list((tmp_path / "o").iterdir()) == []


@pytest.mark.parametrize("src", ["http://example.com/a.mp4", "https://example.com/a.mp3", "-i.mp3",
                                 "/dev/zero.mp3", "pipe:0.mp4"])
def test_refuses_urls_and_odd_names(src, tmp_path):
    with pytest.raises(media.UsageError):
        media.audio(src, tmp_path / "a.mp3")


def test_refuses_unsupported_and_missing(tmp_path):
    text = tmp_path / "notes.txt"
    text.write_text("hi")
    with pytest.raises(media.UsageError):
        media.audio(text, tmp_path / "a.mp3")
    with pytest.raises(media.UsageError):
        media.audio(tmp_path / "gone.mp4", tmp_path / "a.mp3")


def test_refuses_bad_output_suffix(clip, tmp_path):
    with pytest.raises(media.UsageError):
        media.audio(clip, tmp_path / "a.xyz")
    with pytest.raises(media.UsageError):
        media.thumbnail(clip, tmp_path / "a.mp4")


def test_garbage_file_fails_cleanly(tmp_path):
    junk = tmp_path / "junk.mp4"
    junk.write_bytes(b"not media at all" * 10)
    with pytest.raises(media.MediaError):
        media.audio(junk, tmp_path / "a.mp3")
    assert [p.name for p in tmp_path.iterdir()] == ["junk.mp4"]


def test_playlist_cannot_reach_another_protocol(tmp_path):
    """A concat list inside a file may only name local files (-protocol_whitelist file)."""
    lst = tmp_path / "evil.wav"
    lst.write_text("ffconcat version 1.0\nfile 'http://127.0.0.1:9/x.wav'\n")
    with pytest.raises(media.MediaError):
        media.audio(lst, tmp_path / "a.mp3")


def test_missing_ffmpeg(clip, tmp_path, monkeypatch):
    monkeypatch.setenv("PATH", str(tmp_path))
    with pytest.raises(media.ToolNotFound):
        media.audio(clip, tmp_path / "a.mp3")


# --- the command ------------------------------------------------------------------------------

def test_cli_audio_prints_path(clip, tmp_path):
    r = cli("audio", str(clip), "-o", str(tmp_path / "a.mp3"))
    assert r.returncode == 0, r.stderr
    assert r.stdout.strip() == str(tmp_path / "a.mp3")


def test_cli_thumbnail_and_concat(clip, tmp_path):
    assert cli("thumbnail", str(clip), "-o", str(tmp_path / "t.png"), "--at", "1").returncode == 0
    assert cli("concat", str(clip), str(clip), "-o", str(tmp_path / "c.mp4")).returncode == 0


def test_cli_exit_codes(clip, tmp_path):
    out = str(tmp_path / "a.mp3")
    assert cli("audio", str(clip), "-o", out, "--timeout", "0").returncode == 2
    assert cli("audio", "nope.mp4", "-o", out).returncode == 2
    assert cli("audio", str(clip), "-o", out, "--max-seconds", "1").returncode == 1
    assert cli("video").returncode == 2
